version: "3.3"

services:
  app1:
    build: .
    image: app1
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    external: 
      name: app-network
