version: "3.3"

services:
  app1:
    build: .
    image: app1
    container_name: app1
    restart: unless-stopped
    networks:
      - app1-network

  proxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app1
    networks:
      - app1-network

networks:
  app1-network:
    driver: bridge
